version: "3.8"


services:
  
  postgres:
    image: postgres:15
    container_name: loja_postgres
    environment:
      POSTGRES_DB: loja
      POSTGRES_USER: loja_user
      POSTGRES_PASSWORD: loja_pass
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data



volumes:
  postgres_data:
